### ISSUE TITLE
Error when exiting

### ISSUE THREAD

**Issue by doronbehar** [haorenW1025/floatLf-nvim#1]
```
Error detected while processing function floatLf#delete_lf_buffer:
line    6:
E117: Unknown function: CleanupBuffer
```

Tested with a clean nvim environment without any plugins installed..

**Comment by haorenW1025** [comment]
There are some local config that I forgot to add to the plugins...
It should be fixed now, thanks!

**Comment by doronbehar** [comment]
Confirmed.
