### ISSUE TITLE
Focus lf on current buffer

### ISSUE THREAD

**Issue by rlisowski** [haorenW1025/floatLf-nvim#3]
It would be nice to be able to focus `lf` on the current buffer while opening to poke around the current file. I'm not sure if it's already possible.

**Comment by haorenW1025** [comment]
That's a great idea! I make a update and add a command `LfToggleCurrentBuf` which will make the floating terminal cd to your buffer's directory and open up `lf`. You can check if it works. Thanks again for the advice!

**Comment by rlisowski** [comment]
@haorenW1025 it would be better to focus `lf` on current buffer. See PR #4

**Comment by haorenW1025** [comment]
Oh I don't even know that this is possible. Thanks a lot!
