### ISSUE TITLE
Key mappings does not work.

### ISSUE THREAD

**Issue by khalidchawtany** [haorenW1025/floatLf-nvim#5]
Hi,
I like this plugin as it allows opening file in a split and more. When I execute any of the commands the UI is shown. I can navigate and work with lf. However, none of the provided mappings work. 

I can see that the the keys are mapped if I inspect the tmap. However, they do nothing.

FYI: I have the nvr available in the path.

**Comment by haorenW1025** [comment]
Can you check if you have map <c-\\> or \<c-n> to any keys in terminal mode? I'm using the default <c-\\>\<c-n> to get back to normal mode from terminal mode in the plugin so this could be the cause of this problem.

**Comment by khalidchawtany** [comment]
I have not mapped `<c-\><c-n>`. I use it to escape from terminal insert mode. When I press `l` in the `lf` the file is opened in `vim-r`.

**Comment by haorenW1025** [comment]
Hmm that's weird...Can you test it without any configuration like this `nvim -u test.vim` and test.vim should be like
```
set runtimepath+=~/.vim/plugged/floatLf-nvim
```
set the `~/.vim/plugged/floatLf-nvim` to the path of  the plugins

**Comment by khalidchawtany** [comment]
Something very strange going on.
From iTerm I launched an instance of nvim with the config you specified. The keys did nothing. Then I launched `nvim-qt` with my full config. When I press `<c-t>` on a file in the iTerm instance the file is opened in `nvim-qt` :)

The screenshot shows iTerm nvim in front and the nvim-qt in the background.

FYI: I am using `neovim-qt` and configured it to listen on `/tmp/nvimsocket`.

![Screen Shot 2020-03-20 at 1 12 53 PM](https://user-images.githubusercontent.com/1681606/77154669-34721680-6aad-11ea-8c1c-866ff26d032e.png)

**Comment by khalidchawtany** [comment]
It works in terminal if I quit `nvim-qt`. But it does not work in `nvim-qt` :(



EDIT:
works in the `nvim-qt` too if I use it with `nvim-qt qt -- -u ./test.vim`

**Comment by khalidchawtany** [comment]
This is obviously an issue with my config :(

Do you have any pointers on how to debug this?

**Comment by haorenW1025** [comment]
Sorry for the late replied. Actually I don't know if it works in neovim-qt(never used it before). If you open up a terminal in neovim-qt and type `nvr -p {a random file}`, will it open a file in a new tab?

**Comment by khalidchawtany** [comment]
Hi,
I found the issue. It seems that setting `let g:floatLf_autoclose = 1` is causing the problem. The lf terminal is deleted before it gets a chance to execute its commands.

I can work around it by making sure that the `floatLf#delete_lf_buffer()` is called after the open file command is over.
